export const DEFAULT_EVIDENCE_PAGE = 1;
export const DEFAULT_EVIDENCE_LIMIT = 20;
export const MAX_EVIDENCE_LIMIT = 100;

export const EVIDENCE_OBJECT_STORE = Symbol('EVIDENCE_OBJECT_STORE');
export const EVIDENCE_PHOTO_METADATA_EXTRACTOR = Symbol(
  'EVIDENCE_PHOTO_METADATA_EXTRACTOR',
);
export const EVIDENCE_DOCUMENT_ANALYSIS_PROVIDER = Symbol(
  'EVIDENCE_DOCUMENT_ANALYSIS_PROVIDER',
);
export const EVIDENCE_DOCUMENT_CLASSIFIER = Symbol(
  'EVIDENCE_DOCUMENT_CLASSIFIER',
);
